S S 1	0 L_PUSH_10
S S 1	L_PUSH_1
T	T	S STORE_S S 1	L_PUSH_1
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	L_PUSH_1
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	L_PUSH_1
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	L_PUSH_1
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	1	1	L_PUSH_111
S S 1	1	L_PUSH_11
T	T	S STORE_S S 1	1	L_PUSH_11
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	1	L_PUSH_11
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	1	L_PUSH_11
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	1	L_PUSH_11
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	1	L_PUSH_11
S S 1	L_PUSH_1
T	T	S STORE_S S 1	L_PUSH_1
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	L_PUSH_1
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	L_PUSH_1
T	T	T	RESTORE_T	L
S T	PUTI_S S 1	L_PUSH_1
T	T	T	RESTORE_T	L
S T	PUTI_L
L
L
END